### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by ivanlii** [Mogli12/VehicleControlAddon#150]
Hi Mogli, i know you play with the keyboard, but is there any chance in the future for you to look at the analog inputs (clutch and H-shifter gears)?
Now the analog clutch is not working (example: 39% full pressed / 49% released, or other similar values).
Using key press clutch kinda works but there is a problem with gear shifter: when disengaging a gear, even with the clutch pressed, the tractor breaks, losing momentum.
I had hi hopes when i saw back in v0.0.1.0 that you introduced "VCA: clutch axis".
Thanks for sharing!

**Comment by Mogli12** [comment]
Hi,
It should be fixed with v0.0.1.6.
Regards

**Comment by ivanlii** [comment]
0.0.1.7 clutch is working, 
but the second problem still remains: when changing gears (ie. disengaging one gear to engage next one) the brakes are applied.
I suppose analog Neutral has a parking brake...
Thank you.

**Comment by Mogli12** [comment]
No, the brakes are not applied.

**Comment by ivanlii** [comment]
Then i don't know wats happening, if i let the gear on -> tractor rolls, 
but the moment i switch to neutral, even with the clutch pressed -> the vehicle stops.
This of course without acceleration.

**Comment by Mogli12** [comment]
Please read the README.md. If you are looking for a realistic manual transmission then please try of FS19_realManualTransmission.
